# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1024, verbose_name='Hostname')),
                ('connections', models.ManyToManyField(blank=True, related_name='_instance_connections_+', to='mstdn.Instance')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instance',
            },
        ),
    ]
