# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Hostname'),
        ),
    ]
